services:
  service-registry:
    image: amiraliv/service-registry:1.0
    container_name: service-registry-container
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  api-gateway:
    image: amiraliv/api-gateway:1.0
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JWT_SECRET_KEY=3QhZzJvBQAlUOLrZYR3TyZbAj3HLdFiJolx6Khybc0M=
    networks:
      - microservice-network

  auth-service:
    image: amiraliv/auth-service:1.0
    container_name: auth-service-container
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JWT_SECRET_KEY=3QhZzJvBQAlUOLrZYR3TyZbAj3HLdFiJolx6Khybc0M=
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/userservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8129057270
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - microservice-network

  order-service:
    image: amiraliv/order-service:1.0
    container_name: order-service-container
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/orderservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8129057270
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - microservice-network

  product-service:
    image: amiraliv/product-service:1.0
    container_name: product-service-container
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/productservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8129057270
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - microservice-network

#  mysql:
#    image: mysql:latest
#    container_name: mysql-container
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=8129057270
#      - MYSQL_USER=microservices
#      - MYSQL_PASSWORD=8129057270
#    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - microservice-network
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p8129057270" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10

networks:
  microservice-network:
    driver: bridge

#volumes:
#  mysql-data:
